# Generated by Django 5.2.4 on 2025-07-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
                ('auth_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Код авторизации')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='Авторизован')),
                ('invite_code', models.CharField(max_length=20, unique=True, verbose_name='Код приглашения')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to='userauth.profile', verbose_name='Кем приглашен')),
            ],
        ),
    ]
