# Generated by Django 5.2.4 on 2025-07-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_code',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Код авторизации'),
        ),
    ]
