# Generated by Django 5.2.4 on 2025-07-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_profile_auth_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код авторизации'),
        ),
    ]
